setwd('C:\\Users\\jmcdermo\\Documents\\GitHub\\datasciencecoursera\\getting_cleaning_data\\week_two')
#source('http://bioconductor.org/biocLite.R')
#biocLite('rhdf5')
#library('rhdf5')
#created <- h5createFile('example.h5')
#created <- h5createGroup('example.h5', 'foo')
#created <- h5createGroup('example.h5', 'bar')
#created <- h5createGroup('example.h5', 'fooo/baaa')
h5ls('example.h5')